name: Pre-deployment validations

on:
  workflow_call:

jobs:
  eslint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure NPM
        run: |
          npm ci
          npm run lint
